version: "3.7"
services:
    web:
        image: nginx:latest
        ports:
            - "8080:81"
        volumes:
            - .:/app
            - ./etc/nginx/site.conf:/etc/nginx/conf.d/site.conf
        links:
            - php
    php:
        image: php:nginxzendexpressive
        build:
          context: .
          dockerfile: Dockerfile
        volumes:
            - .:/app

