<?php
/**
 * This file generated by Zend\Expressive\Tooling\Factory\ConfigInjector.
 *
 * Modifications should be kept at a minimum, and restricted to adding or
 * removing factory definitions; other dependency types may be overwritten
 * when regenerating this file via zend-expressive-tooling commands.
 */
 
declare(strict_types=1);

return [
    'dependencies' => [
        'factories' => [
            App\Action\AlbumGetAction::class => App\Action\AlbumGetActionFactory::class,
            App\Handler\HelloHandler::class => App\Handler\HelloHandlerFactory::class,
            examplemodule\Handler\IndexHandler::class => examplemodule\Handler\IndexHandlerFactory::class,
        ],
    ],
];
